- .github/workflows/gh-release-chart.yml
fixing
```
Run helm template ./keda \
...
clusterrolebinding.rbac.authorization.k8s.io/keda-operator-hpa-controller-external-metrics serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/keda-operator-webhook serverside-applied
rolebinding.rbac.authorization.k8s.io/keda-operator-auth-reader serverside-applied
apiservice.apiregistration.k8s.io/v1beta1.external.metrics.k8s.io serverside-applied
validatingwebhookconfiguration.admissionregistration.k8s.io/keda-admission serverside-applied
Error from server (NotFound): namespaces "keda" not found
Error from server (NotFound): namespaces "keda" not found
Error from server (NotFound): namespaces "keda" not found
Error from server (NotFound): namespaces "keda" not found
Error from server (NotFound): namespaces "keda" not found
Error …
```
> ensure keda ns in smoketests before chart installation

- .github/workflows/gh-release-chart.yml
check first `deployment` availability before checking `pod` readiness
```
validatingwebhookconfiguration.admissionregistration.k8s.io/keda-admission serverside-applied
error: no matching resources found
Error: Process completed with exit code 1.
```
https://github.com/kedify/charts/actions/runs/10196512985/job/28207435922
> smoke_tests: wait for deployments availability

- .github/workflows/gh-release-chart.yml
This should make the chart release a bit more intuitive
* instead of setting `"true"` when releasing KEDA and `"false"` when releasing http-add-on, there is a select box to choose one or the other
* adding an option to leave the `version` input field blank to allow the pipeline to determine the latest released version of each chart and bump the suffix by 1, e.g. `v2.14.1-3` -> `v2.14.1-4`
> ci: refactor kedify chart release trigger

- http-add-on/values.yaml
Enable attempts for HTTP2 upgrades on the interceptor, this is important for gRPC connections to work out of the box without the necessity to configure anything. Despite the name of the flag, this doesn't force HTTP2, it only configures HTTP transport to enable HTTP2 upgrades but still allows HTTP1.
https://github.com/golang/go/blob/f6c89abf897c4adf7dbd598029f0c12452b4ca25/src/net/http/transport.go#L291-L296
Users can still disable HTTP2 by setting `forceHTTP2: false`.
> http-add-on: attempt HTTP2 upgrade by default

- http-add-on/README.md
- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/values.yaml
this is allowing matching configuration that kustomize has for [e2e tests](https://github.com/kedacore/http-add-on/blob/08c811fe205daaf2bc55c6a46155be2729f21916/config/interceptor/e2e-test/otel/deployment.yaml#L1-L21)
> http-add-on: allow configuring prometheus and otel collectors

- http-add-on/README.md
- http-add-on/templates/interceptor/service-metrics.yaml
- http-add-on/values.yaml
followup to https://github.com/kedify/charts/pull/46, there is also [metrics service](https://github.com/kedacore/http-add-on/blob/08c811fe205daaf2bc55c6a46155be2729f21916/config/interceptor/metrics.service.yaml#L1-L11) necessary for the e2e tests
> http-add-on: metrics service

- http-add-on/values.yaml
Kedify agent doesn't have RBAC to install PDB so disabling this by default.
```
10-01 10:39:54	ERROR	Reconciler error	{"controller": "kedifyconfiguration", "controllerGroup": "install.kedify.io", "controllerKind": "KedifyConfiguration", "KedifyConfiguration": {"name":"kedify","namespace":"keda"}, "namespace": "keda", "name": "kedify", "reconcileID": "29acc29d-ceda-4cad-8257-e4c0d4ae5319", "error": "error while reconciling KEDA installation: failed to install KEDA http addon: failed to create object: poddisruptionbudgets.policy is forbidden: User \"system:serviceaccount:keda:kedify-agent\" cannot create resource \"poddisruptionbudgets\" in API group \"policy\" in the namespace \"keda\""}
```
> http-add-on: disable interceptor pdb

- kedify-agent/templates/agent-deployment.yaml
- kedify-agent/templates/agent-rbac.yaml
1. there was incorrect env variable set when ingress autowiring was disabled resulting in `endpoints`, `services` and `deployments` watches being stuck on missing RBAC
2. when metrics are enabled, they need `statefulsets` and `deployments` RBAC
> agent: configurable autowire and metrics RBAC

- kedify-agent/templates/cr-install/cr-job.yaml
- kedify-agent/templates/crd-install/crd-job.yaml
with istio sidecar, the job has issues
1) the sidecar must be fully operational in order to allow calls to kube-apiservice - we could fix this by adding retry logic
2) the sidecar doesn't terminate by itself - https://github.com/istio/istio/issues/6324 - we would need to add logic to explicit terminate the istio container if it's injected
given these are non-trivial workarounds with potential for issues, and the jobs only create CRD and then CR, I'd like to propose to rather disable istio injection.
closes: https://github.com/kedify/charts/issues/59
> kedify-agent: disable istio sidecar injection for CR and CRD creating jobs

- kedify-agent/templates/crd-install/crd-rbac.yaml
https://github.com/kedify/charts/pull/61 introduces new CRD but the RBAC won't allow installing it
```
$ k logs kedify-agent-crd-install-jxxqs
+ set -o nounset
+ kubectl apply -f /data/
customresourcedefinition.apiextensions.k8s.io/kedifyconfigurations.install.kedify.io unchanged
customresourcedefinition.apiextensions.k8s.io/scalingpolicies.keda.kedify.io unchanged
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "podresourceprofiles.keda.kedify.io", Namespace: ""
from server for: "/data/kedify-podresourceprofile.yaml": customresourcedefinitions.apiextensions.k8s.io "podresourceprofiles.keda.kedify.io" is …
```
> agent: add missing prp RBAC for crd install job

- kedify-agent/templates/agent-deployment.yaml
- kedify-agent/values.yaml
default is the original envoy log format
```
[2024-11-12 10:20:00.993][1][info][main] [source/server/server.cc:426] initializing epoch 0 (base id=0, hot restart version=11.104)
[2024-11-12 10:20:00.993][1][info][main] [source/server/server.cc:428] statically linked extensions:
[2024-11-12 10:20:00.993][1][info][main] [source/server/server.cc:430]   envoy.http.custom_response: envoy.extensions.http.custom_response.local_response_policy, envoy.extensions.http.custom_response.redirect_policy
[2024-11-12 10:20:00.993][1][info][main] [source/server/server.cc:430]   envoy.dubbo_proxy.serializers: dubbo.hessian2
[2024-11-12 10:20:00.993][1][info][main] [source/server/server.cc:430]   envoy.matching.network.input: envoy.matching.inputs.application_protocol, envoy.matching.inputs.destination_ip, …
```
> agent: configurable kedify-proxy log format

- kedify-agent/Chart.yaml
- kedify-agent/templates/NOTES.txt
- kedify-agent/templates/agent-deployment.yaml
- kedify-agent/values.yaml
the preferred form of condition enablement for subchart is by the chart name
https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags
By default, addon chart is disabled and for backwards compatibility, both of these options are supported
```yaml
kedaAddOnsHttp:
enabled: true
keda-add-ons-http:
enabled: true
```
> agent: fix addons subchart install condition name

- http-add-on/templates/scaler/deployment.yaml
The kedify http-add-on contains more configuration knobs through env variables.
> allow setting custom env vars for scaler

- http-add-on/Chart.yaml
- http-add-on/values.yaml
- kedify-agent/Chart.yaml
- kedify-agent/values.yaml
the default limits are not sufficient even for clusters with 100 `HTTPScaledObjects`.
also bumping the agent chart as the addon is a dependency there.
> http addon: increase default memory limits

- .github/workflows/ci-http-add-on.yml
previously this was running on 1.26 - 1.29 which is a bit dated
> ci: run tests on kind 1.31 and 1.30

- http-add-on/values.schema.json
ok:
```
helm template . --set interceptor.resources.requests.memory=500Mi
helm template . --set operator.resources.limits.cpu=1
helm template . --set interceptor.resources.requests.memory=1Gi
helm template . --set operator.resources.limits.cpu=200m
helm template . --set scaler.resources.limits.cpu=200m
helm template . --set interceptor.resources.requests.memory=1G
helm template . --set operator.resources.limits.cpu=42
helm template . --set scaler.resources.limits.cpu=0.5
```
notok:
```
helm template . --set interceptor.resources.requests.memory=1
helm template . --set operator.resources.limits.cpu=-1
helm template . --set operator.resources.limits.cpu=a0.5
helm template . --set operator.resources.limits.aaacpu=1
helm template . --set operator.resources.limits.aaamemory=1G
helm template . …
```
> http-add-on: Fix the json schema for resources

- kedify-agent/Chart.yaml
- kedify-agent/templates/cr-install/cr-configmap.yaml
- kedify-agent/values.yaml
fixes:
* bumping agent to v0.1.9 for node reporting
* reverting part of https://github.com/kedify/charts/pull/73, adding back `name` for keda installation as this is used in the status reporting.
> agent: fix node and status reporting

- http-add-on/Chart.yaml
- http-add-on/values.yaml
Bumping kedify http-add-on images to v0.8.2-1 and chart to v0.8.2-0 - fixing envoy xDS translation for when two `HTTPScaledObjects` reference the same hostname under `.spec.hosts`.
> addon: release v0.8.2-0

- .github/workflows/milestones-tracker.yaml
- .github/workflows/publish-chart-from-release.yaml
Because this repository `main` branch rebases nightly on the upstream, there is no way to track commits between releases, branches and tags. I would like to propose using github milestones for release tracking.
* when a PR affecting `kedify-agent` chart merges, it will get assigned `kedify-agent/next` milestone 
* when a release PR with label `release/kedify-agent` and milestone `kedify-agent/vX.Y.Z` is merged
* all PRs in `kedify-agent/next` will be moved into a `kedify-agent/vX.Y.Z` release milestone
* release `vX.Y.Z` will be generated with release notes aggregating both kedify-agent image CHANGELOG and chart CHANGELOG
* with release published, github will create also a matching tag `kedify-agent/vX.Y.Z`
* tag creation will trigger helm chart publish action publishing `kedify-agent` …
> ci: automated milestones tracker for kedify-agent chart

- keda/values.yaml
Upstream KEDA 2.16.1 has been released
- https://github.com/kedacore/charts/releases/tag/v2.16.1
- https://github.com/kedacore/keda/releases/tag/v2.16.1
This PR prepares for kedify/keda chart release with Kedify-flavoured images based on the latest release.
> keda: default images based on 2.16.1 upstream release

- http-add-on/values.yaml
Upstream http-add-on 0.9.0 has been released
* https://github.com/kedacore/charts/releases/tag/keda-add-ons-http-v0.9.0
* https://github.com/kedacore/http-add-on/releases/tag/v0.9.0
This PR prepares for kedify/http-add-on chart release with Kedify-flavoured images based on the latest release.
> addon: default images based on 0.9.0 upstream release

- http-add-on/values.yaml
fixing the TLS disablement option in the image envoy xDS.
> addon: bump image to v0.9.0-1

- .github/workflows/milestones-tracker.yaml
the job failed to create the release
https://github.com/kedify/charts/actions/runs/12788712352/job/35650558916
```
release PR #90 with milestone: kedify-agent/v0.0.10
creating release kedify-agent/v0.0.10
HTTP 403: Resource not accessible by integration (https://api.github.com/repos/kedify/charts/releases)
```
> ci: add missing permissions for kedify-agent release

- .github/workflows/publish-chart-from-release.yaml
when the release is created, the tag is also created but the push tag event is not triggered
> ci: trigger helm package on release publish

- kedify-agent/files/kedify-configuration.yaml
I removed the `Disabled` as a valid value for the mode in my previous commit so adding it back. I ran `make manifest` on agent repo and blindly copy&pasted the result, but it seems we were missing it there, so opening a PR there as well - https://github.com/kedify/agent/pull/297
W/o this fix the helm chart is not installable, because the job that creates CR (kedify) fails
tested by:
```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
k3d cluster delete || true 2> /dev/null
sleep 0.2
k3d cluster create
for i in ghcr.io/kedify/keda-operator:v2.16.0-1 \
ghcr.io/kedify/http-add-on-scaler:v0.8.1-8 \
ghcr.io/kedify/http-add-on-interceptor:v0.8.1-8 \
ghcr.io/kedify/keda-admission-webhooks:v2.16.0-1 \
ghcr.io/kedify/keda-operator:v2.16.0-1 \ …
```
> adding back the Disabled value

- .github/workflows/milestones-tracker.yaml
fix for
```
Run set -euo pipefail
setting 'kedify-agent/next' milestone for PR #100
GraphQL: Resource not accessible by integration (updatePullRequest)
Error: Process completed with exit code 1.
```
https://github.com/kedify/charts/actions/runs/12932478248/job/36068802207
> ci: add permissions for milestones tracking

- kedify-agent/templates/api-key-secret.yaml
- kedify-agent/values.schema.json
- kedify-agent/values.yaml
why: There are tools like sealed secret operator from Bitnami, SOPS from mozilla or [vault-csi-provider](https://github.com/hashicorp/vault-csi-provider), that allow creating and managing secrets. I think we should allow users to use these or similar tools together w/ the kedify-agent. So the idea is to have a new flag called `agent.createApiKeySecret` (`true` by default) that controls the rendering of k8s secret w/ the apiKey and also the schema validation for `agent.apiKey` field.
status quo:
```
λ helm template .
Error: values don't meet the specifications of the schema(s) in the following chart(s):
kedify-agent:
- agent: Must validate "then" as "if" was valid
- agent.apiKey: String length must be greater than or equal to 10
- agent.apiKey: Does not match pattern '^kfy_[a-z0-9]*$'
- …
```
> Allow for creating the secret w/ api key by other tools

- http-add-on/Chart.yaml
- http-add-on/values.yaml
* image version bump to v0.9.0-4
* improve `HTTPScaledObject` activation heuristic
* add vendor and authors labels to docker build
> http-add-on: release v0.9.0-3

- .github/workflows/milestones-tracker.yaml
Checking if previous partially successful run already created the release, on nonexisting releases, the `gh` command returns non-zero status code
```
$ gh release view kedify-agent/v0.0.14 --json 'tagName'
release not found
$ echo $?
1
```
> ci: idempotent release pipeline

- http-add-on/Chart.yaml
- http-add-on/values.yaml
* image version bump to v0.9.0-5
* envoy xDS: fix context handling during SO activation
* envoy xDS: wait to send only complete snapshots
* envoy xDS: performance improvements
> http-add-on: release v0.9.0-4

- http-add-on/values.yaml
Bumping the interval from 250ms (which gets rejected by kubernetes client go and bumped to 1s anyways) to 20s
```
W0219 15:54:25.513436       1 shared_informer.go:591] resyncPeriod 250ms is too small. Changing it to the minimum allowed value of 1s
```
Can't currently get higher than 20s because of this check
https://github.com/kedacore/http-add-on/blob/61d52ca769f18d6fd112e975a31d131150bee3dc/interceptor/config/validate.go#L29-L36
the description is also incorrect
> -- How often (in milliseconds) the interceptor does a full refresh of its endpoints cache. The interceptor will also use Kubernetes events to stay up-to-date with the endpoints cache changes. This duration is the maximum time it will take to see changes to the endpoints.
This doesn't do any refresh with kube-api, it flushes …
> interceptor: set endpoints cache 20s interval

- kedify-agent/templates/agent-deployment.yaml
- kedify-agent/values.yaml
Add a way to configure log level, format, time encoding and stacktraces enablement.
Adding a bit of structure into the logging settings to be aligned with the rest of the stack (KEDA, HTTP Add-on...)
The old way of setting agent logLevel, has been preserved for backwards compatibility: `agent.logLevel`
But the new preferred way is via `agent.logging.level`
> agent: enhance logging configuration

- .github/workflows/milestones-tracker-http-add-on.yaml
- .github/workflows/milestones-tracker-keda.yaml
- .github/workflows/milestones-tracker-kedify-agent.yaml
- .github/workflows/milestones-tracker-manual.yaml
- .github/workflows/milestones-tracker.yaml
workflow has insufficient permissions and fails for PRs from forks (only forks)
```
setting 'http-add-on/next' milestone for PR #119
GraphQL: Resource not accessible by integration (updatePullRequest)
```
https://github.com/kedify/charts/actions/runs/13438412320/job/37546375862
> ci: fix milestones tracker permissions

- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/values.yaml
support for custom static headers for proxied requests and responses through both `interceptor` and/or `kedify-proxy`.
see also: https://github.com/kedify/http-add-on/pull/105
> http-add-on: custom headers for proxied traffic

- .github/workflows/milestones-tracker-http-add-on.yaml
- .github/workflows/milestones-tracker-keda.yaml
- .github/workflows/milestones-tracker-kedify-agent.yaml
- .github/workflows/milestones-tracker-manual.yaml
- .github/workflows/milestones-tracker.yaml
I was on a wrong path with https://github.com/kedify/charts/pull/122. The release PRs (e.g. https://github.com/kedify/charts/pull/113) are pushed by the bot directly to kedify/charts repo and as a result see the secrets so there are no failures. But PRs from contributors (e.g. https://github.com/kedify/charts/pull/121) come from forks and they don't get to see secrets so this still fails. The automated milestones tracker must be written in a way to not need secrets to support both forked and non-forked workflows.
> ci: milestone tracker without secrets

- http-add-on/Chart.yaml
- http-add-on/values.yaml
* http-add-on: custom headers for proxied traffic ([#121](https://github.com/kedify/charts/pull/121))
* http-add-on: kedify-proxy access log config ([#119](https://github.com/kedify/charts/pull/119))
* interceptor: set endpoints cache 20s interval ([#118](https://github.com/kedify/charts/pull/118))
* image version bump to v0.10.0-0
* https://github.com/kedacore/http-add-on/releases/tag/v0.10.0
* interceptor: custom headers for requests and responses
* envoy xDS: configurable access logs for kedify-proxy
* envoy xDS: dynamic timeout for cold starts
> http-add-on: release v0.10.0-0

- kedify-agent/templates/agent-deployment.yaml
- kedify-agent/values.schema.json
- kedify-agent/values.yaml
In case a customer is using a mix of cloud marketplace integrations - they can specify which agent should be billed under which cloud provider.
> Add optional field cloud-provider for billing

- kedify-agent/templates/agent-deployment.yaml
Supported zap flags in the binary
```
-zap-devel
Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error) (default true)
-zap-encoder value
Zap log encoding (one of 'json' or 'console')
-zap-log-level value
Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
-zap-stacktrace-level value
Zap Level at and above which stacktraces are captured (one of 'info', 'error', 'panic').
-zap-time-encoding value
Zap time encoding (one of 'epoch', 'millis', 'nano', 'iso8601', 'rfc3339' or 'rfc3339nano'). Defaults to 'epoch'.
```
> agent: fix zap logger flags

- kedify-proxy/templates/envoy-deployment.yaml
- kedify-proxy/values.yaml
With kedify-proxy being scalable, the connections need to be drained first by calling this endpoint on the envoy admin port
```
/healthcheck/fail
```
This ensures envoy won't pass readinessProbe so it will be excluded from the service loadbalancing.
> kedify-proxy: preStop hook with readinessProbe

- kedify-agent/templates/agent-deployment.yaml
- kedify-agent/values.yaml
global configuration for service autowiring periodic sync, defaults to 500ms.
Can be further fine-tuned per `ScaledObject` with `http.kedify.io/service-resync-period` annotation.
> autowire: periodic sync service config

- http-add-on/Chart.yaml
- http-add-on/values.yaml
* image version bump to v0.10.0-1
* envoy xDS: throw snapshot update events only when snapshot updated
* operator: fix status target service when using service autowiring
> http-add-on: release v0.10.0-1

- keda/Chart.yaml
- keda/values.yaml
* image version bump to v2.16.1-1
* fix: delete any orphan `HTTPScaledObjects` during the `ScaledObject` update
> keda: release v2.16.1-1

- kedify-proxy/templates/so.yaml
the default `ScaledObject` for kedify-proxy doesn't work with KEDA 2.16.1, the CPU trigger is missing `MetricType`
```
Warning  ScaledObjectCheckFailed  13m (x12 over 13m)    keda-operator  failed to ensure HPA is correctly created for ScaledObject
Warning  KEDAScalerFailed         7m56s (x17 over 13m)  keda-operator  error parsing cpu metadata: unknown metric type: , allowed values are 'Utilization' or 'AverageValue'
```
this is being explicitly checked in the [CPU scaler](https://github.com/kedacore/keda/blob/8e1039cc1bb3a356be0a31993db4cd0ec20f20a8/pkg/scalers/cpu_memory_scaler.go#L84)
> kedify-proxy: fix missing metric type in default SO

- http-add-on/templates/interceptor/deployment.yaml
the metrics service exposes metrics port for interceptor
https://github.com/kedify/charts/blob/2c23303476d6bf05427d62348edcc29cc59acb4a/http-add-on/templates/interceptor/service-metrics.yaml#L12-L14
this is missing in the deployment pod spec which makes it harder to use GKE pod monitoring, because it expects the port to be defined on the pod level too
https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-pod-monitoring
> http-add-on: exposing metrics port on interceptor deployment

- .github/workflows/ci-core.yml
- keda/templates/crds/crd-scalinggroups.yaml
- keda/templates/manager/kedify-rbac.yaml
addition of new `ScalingGroups` CRD and RBAC for KEDA
enable with setting this in values:
```yaml
env:
- name: KEDIFY_SCALINGGROUPS_ENABLED
value: "true"
```
> scaling groups: CRD and RBAC

- kedify-agent/templates/rbacs/can-install-kedify-proxy.yaml
issue:
```
E0403 02:20:18.150160       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: Failed to watch *v1.Deployment: unknown (get deployments.apps)" logger="UnhandledError"
```
> Add missing rbac for kedify proxy installation (watch and list)

- kedify-proxy/Chart.yaml
- kedify-proxy/files/envoy-config.yaml
- kedify-proxy/values.yaml
configuration for overload manager for kedify-proxy envoy. This fixes the warning from envoy startup:
```
[warning][main] [source/server/server.cc:959] There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.global_downstream_max_connections` resource monitor.
```
> kedify-proxy: overload manager config

- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/values.yaml
adding configuration options for envoy:
* [listener `tcp_backlog_size`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#:~:text=by%20this%20listener.-,tcp_backlog_size,-(UInt32Value)%20The) - defaults to kernel param `net.core.somaxconn` or 128. It is not permitted to configure this to less than 128.
* [listener `per_connection_buffer_limit_bytes`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#:~:text=in%20this%20field.-,per_connection_buffer_limit_bytes,-(UInt32Value)%20Soft) - defaults to 1MiB and can be set to overwrite the buffer limit for read and write on downstream
* [cluster `per_connection_buffer_limit_bytes`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#:~:text=will%2 …
> addon: envoy connection buffers and backlog config with higher defaults

- kedify-agent/values.schema.json
- kedify-agent/values.yaml
The schema validation checks for proper `apiKey` and `orgId`
```
- agent.apiKey: String length must be greater than or equal to 10
- agent.apiKey: Does not match pattern '^kfy_[a-z0-9]*$'
- agent.orgId: Does not match format 'uuid'
```
For gitops deployments, it is possible to disable it globally via flag for all helm charts but sometimes that is not desirable. This introduces another option to disable schema validation only for this helm chart by setting `--set disableSchemaValidation=false`
closes: https://github.com/kedify/charts/pull/143
> kedify-agent: make schema validation optional

- http-add-on/Chart.yaml
- http-add-on/values.yaml
* interceptor: envoy connection buffers and backlog config with higher defaults ([#144](https://github.com/kedify/charts/pull/144))
* interceptor: clarify configurable timeouts ([#138](https://github.com/kedify/charts/pull/138))
* http-add-on: exposing metrics port on interceptor deployment ([#136](https://github.com/kedify/charts/pull/136))
* interceptor: explicit int conversion for large envoy values ([#149](https://github.com/kedify/charts/pull/149))
* interceptor: increase default cold-start timeout to 20 min ([#150](https://github.com/kedify/charts/pull/150))
* image version bump to v0.10.0-3
* envoy xDS: config for listener connection buffers and backlog size
* envoy stats sink: add HSO hooks before informers start
* envoy stats sink: group metrics by envoy deployed namespace
* …
> http-add-on: release v0.10.0-3

- kedify-proxy/templates/envoy-deployment.yaml
- kedify-proxy/values.yaml
This PR makes the preStop hook aware of the currently active connections in the envoy. When a particular envoy pod goes to a terminating state, the preStop hook triggers envoy endpoint to ensure it fails the readiness probe and is excluded from traffic routing. Periodic check for active connections with a configurable timeout ensures envoy is not terminated prematurely before all active connections get a chance to finish gracefully.
<details>
<summary>sample logs</summary>
```
[2025-04-08 18:06:32.219][1][info][prestop-hook] Gracefully shutting down kedify-proxy
[2025-04-08 18:06:32.230][1][info][prestop-hook] Try 0/30; active connections: 139
[2025-04-08 18:06:33.240][1][info][prestop-hook] Try 1/30; active connections: 79
[2025-04-08 18:06:34.252][1][info][prestop-hook] Try 2/30; active …
```
> kedify-proxy: preStop hook with active connection check

- kedify-proxy/Chart.yaml
* kedify-proxy: preStop hook with active connection check ([#151](https://github.com/kedify/charts/pull/151))
* kedify-proxy: overload manager config ([#145](https://github.com/kedify/charts/pull/145))
> kedify-proxy: release v0.0.2

- kedify-agent/templates/rbacs/can-install-kedify-proxy.yaml
when performing an upgrade of `kedify-proxy` helm chart, it's possible to get to a situation where `kedify-agent` throws the following error periodically
```
E0409 10:21:39.858684       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go@v0.31.1/tools/cache/reflector.go:243: Failed to watch *v1.Deployment: unknown (get deployments.apps)" logger="UnhandledError"
```
The https://github.com/kedify/charts/pull/141 tried to fix it by adding missing RBAC but `WATCH` and `LIST` methods don't work with `resourceName` which is present on that `ClusterRole` for `deployments` section. This adds both verbs into `ClusterRole` not restricted by any `resourceName`. The reason is the controller-runtime kube client spins up informer cache on demand when a resource is accessed which needs both …
> kedify-agent: rbac to watch, list deployments clusterwide for kedify-proxy installs

- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/values.yaml
When the `ScaledObject` has `kedify-http` scaler and the trigger metadata contains
```yaml
spec:
triggers:
- type: kedify-http
metadata:
maintenancePageEnabled: "true"
```
The traffic is served directly by the `interceptor` and http metrics for the target are discarded by the `scaler`. The `/queue` endpoint on the `interceptor` will still show the values but `scaler` replaces the value with `0` and sets `active` status to `false`.
The values `interceptor.maintenancePage.body` and `interceptor.maintenancePage.responseStatusCode` can be used to configure different default maintenance page behavior. These can be further overwritten by either inlining directly on the `ScaledObject` as
```yaml
spec:
triggers:
- type: kedify-http
metadata:
maintenancePageEnabled: "true"
maintenancePageBody: |- …
```
> interceptor: maintenance page config

- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/values.yaml
Parameters for `kedify-proxy` circuit breakers in the envoy config set by the `interceptor` for each autoscaled application globally. These options can serve as a protection from overloading the autoscaled application during rapid traffic spikes.
> interceptor: parameters for kedify-proxy envoy circuit breakers

- http-add-on/values.yaml
https://github.com/kedify/charts/pull/156 introduced a bug making the interceptor autoscaling trigger too much with the default parameters and scales to 50 very fast even on idle setups.
```
$ k get hpa -nkeda
NAME                                     REFERENCE                                  TARGETS                         MINPODS   MAXPODS
REPLICAS   AGE
keda-hpa-keda-add-ons-http-interceptor   Deployment/keda-add-ons-http-interceptor   cpu: 1%/75%, memory: 118%/90%   1         50
50         177m
```
The default memory requests were very low - 20Mi. Also having 50 interceptors would rarely be a good idea as it's only used for metric aggregation and cached cold-starts.
> interceptor: fix autoscaling defaults with memory request 256Mi

- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/values.yaml
When the `ScaledObject` has `kedify-http` scaler and the trigger metadata contains
```yaml
spec:
triggers:
- type: kedify-http
metadata:
coldStartWaitingPage: "true"
```
Then during the cold-start `interceptor` no longer holds the proxied request but instead responds directly with static page, the http metrics are still accounted for.
The values `interceptor.coldStartWaitingPage.body`, `interceptor.coldStartWaitingPage.responseStatusCode`, and `interceptor.coldStartWaitingPage.retryAfter` can be used to configure different default cold-start waiting page behavior. These can be further overwritten by either inlining directly on the `ScaledObject` as
```yaml
spec:
triggers:
- type: kedify-http
metadata:
coldStartWaitingPageEnabled: "true"
coldStartWaitingPageBody: |-
alternative cold-start …
```
> interceptor: cold-start waiting page configuration

- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/templates/operator/deployment.yaml
- http-add-on/templates/scaler/deployment.yaml
- http-add-on/values.yaml
Use the [coalesce](https://helm.sh/docs/chart_template_guide/function_list/#coalesce) function to set a specific image tag per component [interceptor,scaler,operator].
> [http-addon] Allow to set custom image tag per component

- kedify-agent/Chart.lock
- kedify-agent/Chart.yaml
- kedify-agent/values.yaml
continuation of https://github.com/kedify/charts/pull/183 (the http-addon helm chart had to be released)
consuming the async job that creates crd & cr (SO)
> kedify-agent: fix SO http-add-on subchart dependency for the all-in-one installation

- kedify-agent/values.yaml
- kedify-proxy/templates/envoy-deployment.yaml
- kedify-proxy/values.yaml
ad-hoc release to verify this:
```
helm template oci://ghcr.io/kedify/charts/kedify-proxy --version v0.0.4-uid
```
```
helm template oci://ghcr.io/kedify/charts/kedify-proxy --version v0.0.4-uid | grep runAsU
runAsUser: 101
```
```
helm template oci://ghcr.io/kedify/charts/kedify-proxy --version v0.0.4-uid --set openshift=true | grep runAsU
:tumbleweed:
```
> runAsUser 101 by default

- kedify-agent/files/kedify-podresourceprofile.yaml
syncing the result of `make manifests` from agent's repo
adding support for `prp.spec.target.kind == "scaledobject" && prp.spec.trigger.after == "(de)activated"`
> prp: CRD updated

- http-add-on/templates/interceptor/deployment.yaml
- http-add-on/templates/scaler/deployment.yaml
- http-add-on/values.yaml
The original protocol between http-add-on external-scaler and interceptor is simple REST. There is an upstream issue discussing leveraging the external-scaler gRPC protocol https://github.com/kedacore/http-add-on/issues/97, but that is not suitable for the needs of communication between these two components.
Kedify http-add-on implements a different gRPC protocol called `bridge` and this PR adds configuration options to the chart.
To enable the bridge, set the following section for http-add-on
```yaml
grpcBridge:
enabled: true
```
The external-scaler newly exposes prometheus metrics, there are also new set of metrics for interceptor.
```sh
kedify_grpc_bridge_not_ready_total
kedify_grpc_bridge_reconnect_total
kedify_grpc_bridge_metric_flush_total
kedify_grpc_bridge_metric_flush_error_total …
```
> http-add-on: gRPC bridge between external-scaler and interceptor

- kedify-proxy/Chart.yaml
see also: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.35/v1.35.0
see also: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.35/v1.35.1
> kedify-proxy: bump envoy to v1.35.1
